from __future__ import annotations

from datetime import datetime
from typing import Protocol

from app.repositories.annotation_repository import StoredAnnotation
from app.repositories.artifact_repository import ArtifactCompletionRecord, ArtifactType
from app.repositories.dashboard_repository import DashboardSnapshot
from app.repositories.metric_summary_repository import MetricSummaryItemRecord, MetricSummaryRecord
from app.repositories.oauth_attempt_repository import StoredOAuthAttempt
from app.repositories.record_repository import StoredRecord
from app.repositories.session_repository import StoredSession
from app.repositories.user_repository import StoredUser
from app.schemas.annotation import CreateAnnotationRequest, UpdateAnnotationRequest
from app.schemas.auth import AuthProvider
from app.schemas.record import CreateRecordRequest, CreateRecordResponse, RecordStatus


class UserRepositoryContract(Protocol):
    def get(self, user_id: str) -> StoredUser | None: ...
    def get_by_provider_identity(self, provider: str, provider_subject: str) -> StoredUser | None: ...
    def create(self, user: StoredUser, *, provider_subject: str) -> StoredUser: ...
    def update_profile(self, user_id: str, *, email: str, display_name: str, avatar_url: str | None) -> StoredUser: ...
    def get_or_create_demo_user(self, provider: AuthProvider) -> StoredUser: ...


class SessionRepositoryContract(Protocol):
    def create_for_user(self, user_id: str) -> StoredSession: ...
    def get(self, session_id: str) -> StoredSession | None: ...
    def get_active(self, session_id: str, *, now: datetime | None = None) -> StoredSession | None: ...
    def revoke(self, session_id: str, *, revoked_at: datetime | None = None) -> bool: ...
    def delete(self, session_id: str) -> bool: ...
    def delete_expired(self, *, now: datetime | None = None) -> int: ...


class OAuthAttemptRepositoryContract(Protocol):
    def create(self, *, code_verifier: str, nonce: str, return_path: str) -> tuple[str, StoredOAuthAttempt]: ...
    def consume(self, state: str, *, now: datetime | None = None) -> StoredOAuthAttempt | None: ...
    def delete_expired(self, *, now: datetime | None = None) -> int: ...


class RecordRepositoryContract(Protocol):
    def create(self, request: CreateRecordRequest, *, owner_user_id: str) -> CreateRecordResponse: ...
    def exists(self, record_id: str) -> bool: ...
    def is_owned_by(self, record_id: str, owner_user_id: str) -> bool: ...
    def update_status(self, record_id: str, status: RecordStatus) -> CreateRecordResponse: ...
    def transition(self, *, record_id: str, expected_statuses: tuple[RecordStatus, ...], status: RecordStatus) -> StoredRecord: ...
    def mark_failed(self, *, record_id: str, stage: str, code: str, message: str, retryable: bool) -> StoredRecord: ...
    def retry_failed(self, *, record_id: str) -> StoredRecord: ...
    def get(self, record_id: str) -> StoredRecord | None: ...
    def get_owned(self, record_id: str, owner_user_id: str) -> StoredRecord | None: ...
    def list(self) -> list[StoredRecord]: ...
    def list_owned(self, owner_user_id: str) -> list[StoredRecord]: ...
    def delete_owned(self, record_id: str, owner_user_id: str) -> bool: ...


class ArtifactRepositoryContract(Protocol):
    def prepare_upload(self, *, record_id: str, artifact_type: ArtifactType, storage_path: str, content_type: str, expected_file_size: int, checksum_algorithm: str, expected_checksum: str) -> ArtifactCompletionRecord: ...
    def get(self, *, record_id: str, artifact_type: ArtifactType) -> ArtifactCompletionRecord | None: ...
    def mark_complete(self, *, record_id: str, artifact_type: ArtifactType, storage_path: str, version: str | None = None, generated_from_frame_index: int | None = None, validated_file_size: int | None = None, validated_checksum: str | None = None, object_generation: str | None = None) -> ArtifactCompletionRecord: ...
    def has_completed(self, *, record_id: str, artifact_type: ArtifactType) -> bool: ...
    def get_completed(self, *, record_id: str, artifact_type: ArtifactType) -> ArtifactCompletionRecord | None: ...
    def get_completed_owned(self, *, record_id: str, artifact_type: ArtifactType, owner_user_id: str) -> ArtifactCompletionRecord | None: ...
    def get_completed_for_records(self, record_ids: list[str], artifact_type: ArtifactType) -> dict[str, ArtifactCompletionRecord]: ...
    def list_for_record(self, record_id: str) -> list[ArtifactCompletionRecord]: ...


class MetricSummaryRepositoryContract(Protocol):
    def persist_summary(self, *, record_id: str, items: list[MetricSummaryItemRecord]) -> MetricSummaryRecord: ...
    def get_summary(self, record_id: str) -> MetricSummaryRecord | None: ...
    def get_summary_owned(self, record_id: str, owner_user_id: str) -> MetricSummaryRecord | None: ...
    def get_summaries(self, record_ids: list[str]) -> dict[str, MetricSummaryRecord]: ...


class AnnotationRepositoryContract(Protocol):
    def create(self, record_id: str, request: CreateAnnotationRequest, *, author_user_id: str) -> StoredAnnotation: ...
    def list_for_record(self, record_id: str) -> list[StoredAnnotation]: ...
    def list_for_owned_record(self, record_id: str, owner_user_id: str) -> list[StoredAnnotation]: ...
    def get(self, annotation_id: str) -> StoredAnnotation | None: ...
    def get_for_owned_record(self, annotation_id: str, record_id: str, owner_user_id: str) -> StoredAnnotation | None: ...
    def update(self, annotation_id: str, request: UpdateAnnotationRequest) -> StoredAnnotation: ...
    def delete(self, annotation_id: str) -> None: ...


class DashboardRepositoryContract(Protocol):
    def get_snapshot(
        self,
        owner_user_id: str,
        reference_time: datetime,
    ) -> DashboardSnapshot: ...
